CREATE TABLE [dbo].[TASK](
	[ID_TASK] [int] IDENTITY(1,1) NOT NULL,
	[TASK] [varchar](200) NULL,
	[IS_COMPLETED] [bit] NULL,
	[IS_DELETED] [bit] NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_DATE] [datetime] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TASK] ADD  CONSTRAINT [DF_TASK_IS_COMPLETED]  DEFAULT ((0)) FOR [IS_COMPLETED]
GO

ALTER TABLE [dbo].[TASK] ADD  CONSTRAINT [DF_TASK_IS_DELETED]  DEFAULT ((0)) FOR [IS_DELETED]
GO

ALTER TABLE [dbo].[TASK] ADD  CONSTRAINT [DF_TASK_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[TASK] ADD  CONSTRAINT [DF_TASK_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO
